[project]
name = "infomads-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chen Zhiyang", email = "30455060+chenzhiy2001@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
]

[project.scripts]
infomads-2026 = "infomads_2026:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
